### ISSUE TITLE
Linux support

### ISSUE THREAD

**Issue by ryukinix** [icyphy/ptII#333]
I didn't find anything about, even the software being written in Java. There is some work on this to run the software natively?

**Comment by mehrdadn** [comment]
I haven't tried recently but I would expect it to work fine natively. Have you tried compiling/running it on Linux (perhaps following similar instructions as on OS X)? Feel free to post here if you've run int any issues.

**Comment by ryukinix** [comment]
Thanks for supporting. I will try.

**Comment by ryukinix** [comment]
After clone in the root of repository I did:

```
export PTII=~/ptII
mkdir $PTII
./configure
make fast install
```

I can run the software now as `~/ptII/bin/vergil`
